swagger: "2.0"
info:
  title: Task Management API
  version: 1.0.0
  description: API documentation for Task Management system
host: localhost:3000
basePath: /api
schemes:
  - http
paths:
  /task/createTask:
    post:
      tags:
      - todo app
      summary: Create a new task
      description: Creates a new task.
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/createTaskModel'
      responses:
        200:
          description: Task created successfully
        400:
          description: Invalid input
        500:
          description: Internal server error
          
  /task/editTask:
    put:
      tags:
      - todo app
      summary: Edit a task
      description: Edit an existing task.
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/editTaskModel'
      responses:
        200:
          description: Task updated successfully
        400:
          description: Invalid input
        500:
          description: Internal server error

  /task/viewTasks:
    get:
      tags:
      - todo app
      responses:
        200:
          description: A list of tasks
        500:
          description: Internal server error

  /task/markTaskCompleted:
    post:
      tags:
      - todo app
      summary: Mark a task as completed
      description: Mark a specific task as completed.
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/markTaskCompletedModel'
      responses:
        200:
          description: Task marked as completed
        404:
          description: Task not found
        500:
          description: Internal server error

  /task/deleteTask:
    delete:
      tags:
      - todo app
      summary: Delete a task
      description: Soft delete a task.
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/deleteTaskModel'
      responses:
        200:
          description: Task deleted successfully
        404:
          description: Task not found
        500:
          description: Internal server error

definitions:
  createTaskModel:
    type: object
    properties:
      task_name:
        type: string
      task_title:
        type: string
      task_description:
        type: string
    required:
      - task_title

  editTaskModel:
    type: object
    properties:
      task_id:
        type: integer
      task_name:
        type: string
      task_title:
        type: string
      task_description:
        type: string
    required:
      - task_id
      - task_title

  markTaskCompletedModel:
    type: object
    properties:
      task_id:
        type: integer
    required:
      - task_id

  deleteTaskModel:
    type: object
    properties:
      task_id:
        type: integer
    required:
      - task_id

  taskModel:
    type: object
    properties:
      task_id:
        type: integer
      task_name:
        type: string
      task_title:
        type: string
      task_description:
        type: string
      is_completed:
        type: boolean
      is_deleted:
        type: boolean
      created_on:
        type: string
        format: date-time
      updated_on:
        type: string
        format: date-time
